language: csharp
solution: ConsoleApplication1.sln
script: 
    - sudo apt-get install -y gtk-sharp2
    - nuget restore ConsoleApplication1.sln
matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest

install:
  - nuget restore solution-name.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ConsoleApplication1.sln
  - mono ./UnitTestProject1/UnitTest1.cs


