language: csharp
solution: ConsoleApplication1.sln
script:
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore ConsoleApplication1.sln
